using System.Collections.Generic;
using System.IO;
using Microsoft.Xna.Framework.Graphics;

namespace PrimevalTitmouse
{
    public class Data
    {
        public string[] Jodi_Initial_Letter;
        public string[] Bedding_Still_Wet;
        public string[] Bladder_Continence_Min;
        public string[] Bladder_Continence_Orange;
        public string[] Bladder_Continence_Red;
        public string[] Bladder_Continence_Yellow;
        public string[] Bladder_Continence_Green;
        public string[] Bladder_Green;
        public string[] Bladder_Yellow;
        public string[] Bladder_Orange;
        public string[] Bladder_Red;
        public string[] Bladder_Leak;
        public string[] Bowel_Continence_Min;
        public string[] Bowel_Continence_Orange;
        public string[] Bowel_Continence_Red;
        public string[] Bowel_Continence_Yellow;
        public string[] Bowel_Continence_Green;
        public string[] Bowels_Green;
        public string[] Bowels_Yellow;
        public string[] Bowels_Orange;
        public string[] Bowels_Red;
        public string[] Bowels_Leak;
        public string[] Cant_Remove;
        public string[] Change_Underwear;
        public string[] Change_Underwear_Pants;
        public string[] Change_Underwear_by_Npc;
        public string[] Change_Underwear_Pants_by_Npc;
        public string[] Change_Destroyed;
        public string[] Change_Other_Destroyed;
        public string[] Getting_Changed_Destroyed;
        public string[] Change_Requires_Pants;
        public string[] Change_Requires_Home;
        public string[] Change_At_Home;
        public string[] Drink_Water_Source;
        public string[] Food_Low;
        public string[] Food_None;
        public string[] LookPants;
        public string[] Diaper_Change_Dialog;
        public string[] Change_Other_Dialog;
        public string[] Mess_Accident;
        public string[] Mess_Attempt;
        public string[] Mess_Voluntary;
        public string[] Messed_Bed;
        public string[] Pee_Attempt;
        public string[] Pee_Overflow;
        public string[] Pee_Toilet;
        public string[] Pee_Toilet_Attempt;
        public string[] Pee_Voluntary;
        public string[] PeekWaistband;
        public string[] Poop_Attempt;
        public string[] Poop_Overflow;
        public string[] Poop_Toilet;
        public string[] Poop_Toilet_Attempt;
        public string[] Poop_Voluntary;
        public string[] Spot_Washing_Bedding;
        public string[] Still_Soiled;
        public string[] Should_Change;
        public Dictionary<string, string[]> Night;
        public string Underwear_Clean;
        public string Underwear_Drying;
        public string EasyMode_On;
        public string EasyMode_Off;
        public string[] Underwear_Messy;
        public Dictionary<string,Container> Bed_Options;
        public Dictionary<string, Container> Pants_Options;
        public Dictionary<string, Container> Underwear_Options;
        public string[] Underwear_Wet;
        public Dictionary<string, Dictionary<string, float>> Villager_Friendship_Modifier;
        public Dictionary<string, Dictionary<string, string[]>> Villager_Reactions;
        public Dictionary<string, Dictionary<string, Dictionary<string, string>>> Villager_Underwear_Options;
        public Dictionary<string, Dictionary<string, Dictionary<string, Dictionary<string, string[]>>>> Villager_Potty_Dialogs;
        public Dictionary<string, NpcChangingOptions> Villager_Changing_Options;
        public Dictionary<string, NpcPottyOptions> Villager_Potty_Options;
        public string[] Wake_Up_Underwear_State;
        public string[] Washing_Bedding;
        public string[] Washing_Underwear;
        public string[] Overwashed_Underwear;
        public string[] Water_Low;
        public string[] Water_None;
        public string[] Wet_Accident;
        public string[] Wet_Attempt;
        public string[] Wet_Bed;
        public string[] Wet_Voluntary;
        public Dictionary<string, Consumable> Consumables;
        public Dictionary<string, Debuff> Debuffs;
        public Dictionary<string, Dictionary<string, string>> Underwear_States;
        public string[] Passby;

    }
}
