name: Build and Release

on:
  push:
    branches:
      - main
      - storage-fix
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      # 1. Bump version and push tag
      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          DEFAULT_BUMP: patch
          # If 1.6.5 exists, it will try 1.6.6 etc
          RELEASE_BRANCHES: main,storage-fix

      - name: Build
        run: dotnet build Regression/Regression.csproj -c Release /p:ModVersion=${{ steps.tag_version.outputs.new_tag }} /p:DialogueVersion=${{ steps.tag_version.outputs.new_tag }} /p:IgnoreModBuildCheck=true

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: |
            ## Changes in this version
            ${{ steps.tag_version.outputs.changelog }}
          files: |
            Releases/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
